## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  ## Hibernate Properties
  jpa:
    hibernate:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: bankdb
    password: bankdb
    # Initialize the datasource with available DDL and DML scripts
    initialization-mode: always
  data :
      web :
          pageable :
              size-parameter : size
              page-parameter : page
              default-page-size : 10
              one-indexed-parameters : true
              max-page-size : 2000

server:
  port: 9090

# JWT (Token for auth)
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000